---
kind: Pod
apiVersion: v1
metadata:
  name: etcd
  namespace: kube-system
  labels:
    name: etcd
  annotations:
    prometheus.io.port: "2379"
spec:
  hostNetwork: true
  containers:
  - name: etcd
    image: gcr.io/google_containers/etcd-amd64:{{ kubernetes_versions[hostk8s|default(defaultk8s)]["etcd"] }}
    command:
    - etcd
    args:
    - --name={{ private_hostname }}
    - --listen-peer-urls=http://{{ ansible_default_ipv4["address"] }}:2380
    - --listen-client-urls=http://{{ ansible_default_ipv4["address"] }}:2379,http://127.0.0.1:2379
    - --data-dir=/var/etcd/data
    - --advertise-client-urls=http://{{ private_hostname }}:2379
    - --initial-advertise-peer-urls=http://{{ private_hostname }}:2380
    - --initial-cluster-state=new
    - --initial-cluster={{ groups['master'] | map('extract', hostvars, 'private_hostname') | map('regex_replace', '(.*)', '\\1=http://\\1:2380') | join(',') }}
    resources:
      requests:
        cpu: 200m
    ports:
    - containerPort: 2380
      hostPort: 2380
      name: serverport
    - containerPort: 2379
      hostPort: 2379
      name: clientport
    volumeMounts:
    - name: etcd
      mountPath: "/var/etcd"
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    securityContext:
      seLinuxOptions:
        type: unconfined_t
  volumes:
  - name: etcd
    hostPath:
      path: "/var/lib/etcd"
  - name: etcssl
    hostPath:
      path: /etc/ssl
