---
kind: Pod
apiVersion: v1
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    name: kube-controller-manager
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/kube-controller-manager-amd64:{{ kubernetes_versions[hostk8s|default(defaultk8s)]["images"] }}
    command:
    - /usr/local/bin/kube-controller-manager
    args:
    - --v=4
    - --leader-elect=true
    - --address=0.0.0.0
    - --port=10252
    - --kubeconfig=/etc/kubernetes/pki/controller-manager/kubeconfig

    # Flags to make service accounts work
    - --root-ca-file=/etc/kubernetes/pki/controller-manager/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/controller-manager/service-accounts.key

    # Pod networking
    - --cluster-cidr={{ pod_cidr }}
    - --service-cluster-ip-range=10.0.0.0/16
    - --cloud-provider=aws
    - --cluster-name=kubernetes_{{ env_name }}
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        path: "/healthz"
        port: 10252
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 10252
      hostPort: 10252
    volumeMounts:
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: pki-controller-manager
      mountPath: /etc/kubernetes/pki/controller-manager
      readOnly: true
  volumes:
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: pki-controller-manager
    hostPath:
      path: /etc/kubernetes/pki/controller-manager
