---
kind: Pod
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    name: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler-amd64:{{ kubernetes_versions[hostk8s|default(defaultk8s)]["images"] }}
    command:
    - /usr/local/bin/kube-scheduler
    args:
    - --v=4
    - --leader-elect=true
    - --address=0.0.0.0
    - --port=10251
    - --leader-elect
    - --kubeconfig=/etc/kubernetes/pki/scheduler/kubeconfig
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 10251
      hostPort: 10251
    volumeMounts:
    - name: pki
      mountPath: /etc/kubernetes/pki/scheduler
      readOnly: true
  volumes:
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki/scheduler

