---
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    component: kube-proxy
    ignore_on_drain: "true"
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/kube-proxy-amd64:{{ kubernetes_image_version }}
    resources:
      requests:
        cpu: 100m
    command:
    - kube-proxy
    - --kubeconfig=/etc/kubernetes/pki/kube-proxy/kubeconfig
    - --cluster-cidr=10.244.0.0/16
    - --resource-container=""
    - --v=2
    securityContext:
      privileged: true
    volumeMounts:
    - name: pki
      mountPath: /etc/kubernetes/pki/kube-proxy
      readOnly: true
  volumes:
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki/kube-proxy

